//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace h3_web.Controllers.models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_Medicos_Models : DbContext
    {
        public DB_Medicos_Models()
            : base("name=DB_Medicos_Models")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Administrador> Administrador { get; set; }
        public DbSet<Cita> Cita { get; set; }
        public DbSet<Horario> Horario { get; set; }
        public DbSet<Nomina> Nomina { get; set; }
        public DbSet<Orden> Orden { get; set; }
        public DbSet<Paciente> Paciente { get; set; }
        public DbSet<Persona> Persona { get; set; }
        public DbSet<Procedimiento> Procedimiento { get; set; }
        public DbSet<Profesional> Profesional { get; set; }
    }
}
