//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace h3_web.Controllers.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orden
    {
        public Orden()
        {
            this.Paciente = new HashSet<Paciente>();
        }
    
        public string Cod_Orden { get; set; }
        public string Cod_Cita { get; set; }
        public string Diagnostico { get; set; }
        public string Medicamento { get; set; }
        public string Recomendacion { get; set; }
        public string Remision { get; set; }
    
        public virtual Cita Cita { get; set; }
        public virtual Procedimiento Procedimiento { get; set; }
        public virtual ICollection<Paciente> Paciente { get; set; }
    }
}
